/* All RFC 9783 ECDSA curves for ECC_MIN_KEY_SZ boundary tests. */
#ifndef WOLFCOSE_TEST_EAT_PSA_MIN_KEY_H
#define WOLFCOSE_TEST_EAT_PSA_MIN_KEY_H

#define HAVE_ECC
#define HAVE_ALL_CURVES
#define ECC_TIMING_RESISTANT
#define NO_RSA
#define WOLFSSL_SHA384
#define WOLFSSL_SHA512

#endif /* WOLFCOSE_TEST_EAT_PSA_MIN_KEY_H */
